spring:
  application:
    name: "integroq"
  ai:
    openai:
      api-key: ${GROQ_API_KEY:YOUR_GROQ_API-KEY}
      base-url: ${GROQ_BASE_URL:https://api.groq.com/openai}
      chat:
        options:
          model: ${GROQ_MODEL:openai/gpt-oss-120b}